<a href="https://colab.research.google.com/github/uzymaru/GeneticAlgorithm/blob/main/M_Rizky_Fauzy_Mustafa_A11202013086_UASKB_AlgoritmaGenetika.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math
import random

In [44]:
class algo_genetika :
# membuat algoritma genetika
# misalkan ada persamaan a+2b+3c+4d = 30
# maka buat algoritma genetika untuk mencari nilai a,b,c, dan d

	populasi = 6 #jumlah chromosome
	gen = ["a", "b", "c", "d"] #nilai gen abcd
	batas_nilai = {
		'min' : 0,
		'max' : 10
	} #nilai per gen 0-10
	crossover = 50/100 #persen
	mutasi_rate = 10/100 #persen
	total_gen = 24
# total_gen     = (jumlah gen dalam chromosome) * jumlah populasi
# = 4 * 6
# = 24
	next_gen = np.arange(4)
	stop = False

#inisialisasi chromosome secara random    
	def __init__(self):
		self.first_chrom = np.random.randint(low=self.batas_nilai['min'], high=self.batas_nilai['max'], size=(self.populasi, len(self.gen)))
		print("Inisialisasi")
		print(self.first_chrom)
		print(" ")

#evaluasi chromosome
	def evaluasi_chrom(self, chrom, generasi):
		# mencari fungsi objektif
		# fungsi_objektif(chromosome) = | (a+2b+3c+4d) – 30 |
		print("Generasi ke-"+str(generasi+1)+"")
		
		jumlah_chromo = len(chrom)
		o = np.arange(jumlah_chromo)   
		fitness = np.arange(jumlah_chromo, dtype='f')
		
		for x in range(len(chrom)):
		
			#FUNGSI OBJEKTIF 
			#fo=fungsi_objektif(chromosome[x])=o[x]
			fo = abs((chrom[x][0]+2*chrom[x][1]+3*chrom[x][2]+4*chrom[x][3])-30)
			o[x] = fo
			
			#SELEKSI CHROMOSOME, DAN MENCARI FITNESS
			fitn = 1/(fo+1)
			
			fitness[x] = fitn
			if(fitn == 1):
				self.stop = True
			print("Chromosome {0} : {1}, fitness = {2}".format(x+1, np.array2string(chrom[x], separator=','), fitn))
		print(o)
		
        
#probabilitas
		Probab = np.arange(jumlah_chromo, dtype='f')
		# print(fitness)
		total_fitness = fitness.sum() #rumus total fitness
		Probab = fitness / total_fitness #rumus mencari probabilitas
		print("Total fitness : {}".format(str(total_fitness)))
		print("Rata-rata fitness : {}".format(str(np.average(fitness))))
		print("Probabilitas : {}".format(np.array2string(Probab, separator=',')))
		print("Probabilitas Paling Tinggi : {}, Pada chromosome ke {}".format(Probab[Probab.argmax()], str(Probab.argmax()+1)))
		print("Chromosome yang mungkin terpilih pada generasi selanjutnya : {}".format(np.array2string(chrom[Probab.argmax()], separator=',')))
		print("")
		print("")
		self.next_gen = chrom[Probab.argmax()]

#mencari nilai kumulatif
		C = np.arange(jumlah_chromo, dtype='f')
		total_x = 0
		for x in range(len(Probab)):
			total_x += Probab[x]
			C[x] = total_x

#roulette wheel sebanyak jumlah populasi
		R = np.random.sample(len(fitness))
		chrom_baru = np.arange(jumlah_chromo*len(self.gen)).reshape(jumlah_chromo, len(self.gen))


#mencari chromosome baru dari roulette wheel
		for y in range(len(R)):
			for k in range(len(chrom_baru)):
				if(R[y] < C[0]):
					chrom_baru[y] = chrom[0]
				elif((C[k-1] < R[y]) & (R[y] < C[k])):
					chrom_baru[y] = chrom[k]

#mencari crossover chromosome
		R = np.random.sample(jumlah_chromo)
		index_chrome_induk = [] # [1,2,3, ...]
		for p in range(len(R)):
			if(R[p] < self.crossover):
				index_chrome_induk.append(p)
                
#menentukan posisi crossover
		posisi_cros = np.random.randint(low=1, high=len(self.gen), size=len(index_chrome_induk))

#menentukan posisi cut-point crossover
		offspring = np.arange(len(self.gen)*len(index_chrome_induk)).reshape(len(index_chrome_induk), len(self.gen))
		for i_parent in range(len(index_chrome_induk)):
			index_chrome_1 = index_chrome_induk[i_parent]
			if(i_parent == len(index_chrome_induk)-1):
				index_chrome_2 = index_chrome_induk[0]
			else:
				index_chrome_2 = index_chrome_induk[i_parent+1]
			#melakukan cut-point
			cut_point = posisi_cros[i_parent]
			for p in range(len(chrom_baru[index_chrome_1])):
				if(p >= posisi_cros[i_parent]):
					offspring[i_parent][p] = chrom_baru[index_chrome_2][p]
				else:
					offspring[i_parent][p] = chrom_baru[index_chrome_1][p]

		for x in range(len(offspring)):
			chrom_baru[index_chrome_induk[x]] = offspring[x]
            
#mutasi chromosome
		total_gen = len(chrom) * len(chrom[0])
		jum_mutasi = self.mutasi_rate * total_gen #rumus menghitung jumlah mutasi
		jum_mutasi = int(jum_mutasi)

		random_i_mutasi = np.random.randint(low=0, high=total_gen, size=jum_mutasi)

		for x in range(len(random_i_mutasi)):
			index_mutasi = random_i_mutasi[x]
			byk_kromosom = len(chrom)
			byk_gen = len(chrom[0])
			random_value = random.randint(self.batas_nilai['min'], self.batas_nilai['max'])
			if(index_mutasi <= byk_gen):
				#jika index_mutasi <= banyak gen, maka akan mengganti
				#gen pada chromosome baru yang ke-1
				chrom_baru[0][index_mutasi-1]
			else:
				#POSISI Y DARI KROMOSOM, UNTUK MENCARI INDEX
				posisi_y = index_mutasi/byk_gen
				posisi_y = int(posisi_y)
				posisi_x = index_mutasi % byk_gen
				chrom_baru[posisi_y][posisi_x] = random_value
		return chrom_baru

	def do_now(self):
		chromosome_current = self.first_chrom
		for generasi in range(0, self.total_gen):
			if(self.stop != True):
				chromosome_current = self.evaluasi_chrom(chromosome_current, generasi)
		print("----------------------------------------------------------------------")
		print("Chromosome yang terpilih adalah")
		print(self.next_gen)

run = algo_genetika()
run.do_now()

Inisialisasi
[[6 7 1 7]
 [2 0 6 9]
 [0 5 8 0]
 [5 5 6 0]
 [1 7 8 3]
 [4 6 8 0]]
 
Generasi ke-1
Chromosome 1 : [6,7,1,7], fitness = 0.045454545454545456
Chromosome 2 : [2,0,6,9], fitness = 0.037037037037037035
Chromosome 3 : [0,5,8,0], fitness = 0.2
Chromosome 4 : [5,5,6,0], fitness = 0.25
Chromosome 5 : [1,7,8,3], fitness = 0.045454545454545456
Chromosome 6 : [4,6,8,0], fitness = 0.09090909090909091
[21 26  4  3 21 10]
Total fitness : 0.6688552
Rata-rata fitness : 0.11147586
Probabilitas : [0.06795873,0.05537378,0.29901838,0.37377298,0.06795873,0.13591745]
Probabilitas Paling Tinggi : 0.3737729787826538, Pada chromosome ke 4
Chromosome yang mungkin terpilih pada generasi selanjutnya : [5,5,6,0]


Generasi ke-2
Chromosome 1 : [4,6,8,0], fitness = 0.09090909090909091
Chromosome 2 : [0,5,8,0], fitness = 0.2
Chromosome 3 : [0,5,8,0], fitness = 0.2
Chromosome 4 : [0,6,8,0], fitness = 0.14285714285714285
Chromosome 5 : [5,5,6,0], fitness = 0.25
Chromosome 6 : [4,6,8,0], fitness = 0.09090909